### PR TITLE
[Feature] Support multi model, config and vae load form HuggingFace

### PR DESCRIPTION
**Pull request by kiuchikeisuke**
# Summary
- Support multi(max 3) model, config and vae load form HuggingFace

# Details
- remove model_filename input,config_filename input, vae_filename input
-add model_url2,3, config_url2,3 and vae_url2,3 input
----

# 概要
- モデル、configファイル、VAEファイルのHuggingFaceからの複数(最大３つ)読み込み対応

# 修正内容詳細
- model_filename input,config_filename input, vae_filename のInput欄を削除
- model_url2,3, config_url2,3, vae_url2,3のInput欄を追加

### CODE REVIEW

**Comment by sa-shiro** [comment]
tbh, i dont see the need for downloading multiple models at once, unless you have paid for extra storage / paid for colab as you would run out of storage on either google colab or google drive with downloading multiple ones pretty fast, easier to either scrap the entire env or delete models and run the dl models task again (as most users are not paying for neither drive nor colab, id say at least)

**Comment by kiuchikeisuke** [comment]
@sa-shiro (cc: @ddPn08 )
There are two reasons.
The first is because I believe that if you run the process over and over again, you may run out of free quota units. (Perhaps, just starting the WebUI consumes computing units...?) So I think it would be better to be able to load multiple models at the same time if possible.
The second is needed to merge models. Of course, force_model_download_locally needs to be checked to save space on GoogleDrive.

Translated with www.DeepL.com/Translator (free version)

---- 
理由は２つあります。
１つ目は何度も処理を走らせると無料枠のユニットを使い切ってしまう可能性があると思っているからです。（恐らくですが、WebUIを起動するだけでコンピューティング ユニットが消費される...?）なので、可能なら同時に複数のモデルを読み込めた方が良いかなと思ってます。
２つ目はモデルをマージするために必要です。勿論GoogleDriveの容量を節約するためにforce_model_download_locallyにはチェックを入れる必要がありますが。

**Comment by sa-shiro** [comment]
hence i said "delete the models" ^^
if you generate a lot of images and using more than 2 models, you run out of space pretty fast thats why i dont see a need for it :D
however, others may have a use for it, not the majority, but still 
lets see what the repo owner says :)

**Comment by kiuchikeisuke** [comment]
@sa-shiro (cc: @ddPn08 )

> hence i said "delete the models" ^^

Ah, I see, I was mistaken...surely you can delete the model.

> if you generate a lot of images and using more than 2 models, you run out of space pretty fast thats why i dont see a need for it :D
however, others may have a use for it, not the majority, but still

I agree with these opinions. I think it is up to two to load and I think it is a minority feature.
(Or maybe it would be better to have a separate Colab for model merging... 🤔 )


> lets see what the repo owner says :)

ok ^^

---
> hence i said "delete the models" ^^

確かにモデルを削除するなら大丈夫ですね…

> if you generate a lot of images and using more than 2 models, you run out of space pretty fast thats why i dont see a need for it :D
however, others may have a use for it, not the majority, but still

この辺は自分も同意見です。２つより多いモデルをロードする可能性は低いと思うし、マイノリティな機能かなと思います。
（あるいは、モデルをマージするためのColabを別に用意したほうが良いかも…）

**Comment by sa-shiro** [comment]
I apologize for my somewhat ignorance, i didnt think wide enough before posting that :D other people might have a use for it, and its actually a good idea to swap between 2-3 models quickly so actually a great addition
again i sincerely apologize

**Comment by kiuchikeisuke** [comment]
Let's put our opinions in order.
Good: It would be quicker to switch between models if multiple models could be loaded at once.
Good: Models can be merged.
Bad: Loading too many models uses up resources.

> its actually a good idea to swap between 2-3 models quickly so actually a great addition

Hmm... 🤔 If so, ↑I think this idea is quite good. That is, limit the number of models that can be set to 2 (or 3).
That way, the set models can be switched quickly and models can be merged.In addition, the input fields in Colab would be easier to understand.

If there are no problems, I would like to modify the functionality based on the above proposal, depending on the owner's opinion.

---

いちど意見を整理してみましょう。
・Good：複数のモデルを一度に読み込めた方が素早く切り替えられる
・Good：モデルのマージを行える
・Bad：多くのモデルを読み込むとリソースを使い切ってしまう

> its actually a good idea to swap between 2-3 models quickly so actually a great addition

だとすると、↑この案はかなり良い気がします。つまり、設定できるモデルの数を２個（あるいは３個）に制限する。
そうすれば設定したモデルは素早く切り替えられるし、モデルのマージもできる。さらにColabでの入力欄も解りやすくなる

オーナーの意見次第ですが、問題なければ↑の案で機能を修正しようかなと思います。

**Comment by kiuchikeisuke** [comment]
@sa-shiro (cc @ddPn08 )
Let's put our opinions in order.
Good: It would be quicker to switch between models if multiple models could be loaded at once.
Good: Models can be merged.
Bad: Loading too many models uses up resources.

> its actually a good idea to swap between 2-3 models quickly so actually a great addition

Hmm... 🤔 If so, ↑I think this idea is quite good. That is, limit the number of models that can be set to 2 (or 3).
That way, the set models can be switched quickly and models can be merged.In addition, the input fields in Colab would be easier to understand.

If there are no problems, I would like to modify the functionality based on the above proposal, depending on the owner's opinion.

---

いちど意見を整理してみましょう。
・Good：複数のモデルを一度に読み込めた方が素早く切り替えられる
・Good：モデルのマージを行える
・Bad：多くのモデルを読み込むとリソースを使い切ってしまう

> its actually a good idea to swap between 2-3 models quickly so actually a great addition

だとすると、↑この案はかなり良い気がします。つまり、設定できるモデルの数を２個（あるいは３個）に制限する。
そうすれば設定したモデルは素早く切り替えられるし、モデルのマージもできる。さらにColabでの入力欄も解りやすくなる

オーナーの意見次第ですが、問題なければ↑の案で機能を修正しようかなと思います。

**Comment by kiuchikeisuke** [comment]
Updated Feature.
- Limit the number of loads to 3

**Comment by ddPn08** [comment]
Thank you!
I don't think it will be inconvenient for users who don't need multiple models, so I'll merge them as they are.

---

ありがとうございます！
特に複数モデルが必要ないユーザーが不便になるようなこともないと思うのでこのままマージします。

**Review by ddPn08 — APPROVED** [review]

**Pull request merged**
