### PR TITLE
updated automatic1111.ipynb

### PR DESCRIPTION
**Pull request by sa-shiro**
- changed model to a better alternative (Anything v3)
- added VAE support at launch
- added the option to only save outputs to gdrive (models won't be uploaded to gdrive)
- reordered some entries

### CODE REVIEW

**Comment by sa-shiro** [comment]
vscode automatically added lots of \n's im sorry for this as i didnt notice this lol

**Comment by ddPn08** [comment]
I'm sorry. I missed this PR. I will check it now.

**Comment by sa-shiro** [comment]
dont worry :D i hope i didnt mess anything up as i accidentally did lol (hence the 4 forced pushes lol) 
final version should work as expected, if i didnt mess anything up again in the last commit xD

**Review by ddPn08 — APPROVED** [review]

**Comment by ddPn08** [comment]
Fixed some things to fit the `data_dir` concept.

**Pull request merged**
